review

diff --git a/.github/workflows/test-action.yaml b/.github/workflows/test-action.yaml
--- a/.github/workflows/test-action.yaml
+++ b/.github/workflows/test-action.yaml
@@ -10,7 +10,6 @@ on:
       - main
 
 jobs:
-
   automated-tests:
     runs-on: ubuntu-latest
 
@@ -73,3 +72,15 @@ jobs:
           wait-for-results: "yes"
           domain: "https://api-staging.heal.dev"
           comment-on-pr: "yes"
+      - name: Assert Result my-action_old
+        run: |
+          if [[ "${{ steps.my-action_old.outputs.execution-id }}" == "" ]]; then
+            echo "Action failed to return an execution ID."
+            exit 1
+          fi
+      - name: Assert Result my-action_new
+        run: |
+          if [[ "${{ steps.my-action_new.outputs.execution-id }}" == "" ]]; then
+            echo "Action failed to return an execution ID."
+            exit 1
+          fi
